import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Lora } from "next/font/google";
import { Ubuntu } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });
const ubuntu = Ubuntu({
  subsets: ["cyrillic"],
  weight: "400",
  variable: "--font-ubuntu"
});
const lora = Lora({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-lora"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${lora.variable} ${ubuntu.variable} bg-background`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
